### ISSUE TITLE
Plugins usage

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#13]
I've been using my own [CssMinProcessor](https://github.com/zimmicz/posts-zimmi-cz/blob/master/plugins/CssMin/src/CssMinProcessor.php) with v1. Is it possible to define such a plugin with v2 as well? How does it work exactly? Docs doesn't say much about this.

**Comment by ludovicchabant** [comment]
It's indeed possible to make plugins for v2, although of course they would have to be written in Python. There is some documentation available non-officially here: http://bolt80.com/piecrust/en/latest/code/ (I'm still writing it). Note that PieCrust v2 ships with a `cleancss` processor out of the box, although it is disabled by default (since it requires you to install `cleancss` with `npm install cleancss`).

To enable it, along with the `uglifyjs` (same idea, you need to install it with `npm install uglifyjs`), you do this in your site config:

```
baker:
  assets_dirs:
    assets:
      processors: all
```

If you just want `cleancss` and not `uglifyjs`, you can go `processors: all -uglifyjs`.
