### ISSUE TITLE
Please consider updating requirements.txt

### ISSUE THREAD

**Issue by kseistrup** [ludovicchabant/PieCrust2#14]
Please consider updating requirements.txt – more of the requirements are outdated versions.

Installing PieCrust2 on a Linux distro like ArchLinux breaks havoc: a `pip install piecrust2` will uninstall newer versions and install outdated versions of packages that are already in ArchLinux.  One example is `pygments`: PieCrust2 wants version 1.6, but the current version available on pygments.org (and in ArchLinux) is 2.0.2.

Cheers.

**Comment by ludovicchabant** [comment]
Indeed, although that's why it's recommended to install these kinds of programs in a virtualenv :)
But good point, because it made me realize `pip` is not quite installing and upgrading packages the way I thought it was..... d'oh! I'll push the fix soon, but right now I'm fighting a moderately important bug. Thanks!

**Comment by kseistrup** [comment]
I agree about virtualenv. However, some day someone will make an AUR package for ArchLinux that installs PieCrust2 systemwide, so PC2 might as well try to use the newest versions of third party modules,

Please take your time. :)

**Comment by ludovicchabant** [comment]
Fixed with 95ac807d98129a82278211668f43b789e73da61f!

**Comment by kseistrup** [comment]
Cool, thanks.
