### ISSUE TITLE
pip installation fails

### ISSUE THREAD

**Issue by zimmicz** [ludovicchabant/PieCrust2#16]
`sudo pip3 install piecrust` ends with `Could not find a version that satisfies the requirement piecrust (from versions: 2.0.0-alpha1, 2.0.0-alpha2, 2.0.0-alpha3, 2.0.0-alpha4, 2.0.0a5, 2.0.0a6, 2.0.0a7, 2.0.0a8, 2.0.0a9)`

`sudo pip3 install --pre piecrust` works, but there are some issues with this version and flat hierarchy: going to bl.og/year/post-name results in:

```
%d format: a number is required, not NoneType
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/piecrust/serving.py", line 98, in _run_piecrust
    response = self._try_serve_page(app, environ, request)
  File "/usr/local/lib/python3.4/dist-packages/piecrust/serving.py", line 171, in _try_serve_page
    route_metadata, MODE_PARSING)
  File "/usr/local/lib/python3.4/dist-packages/piecrust/sources/posts.py", line 55, in findPagePath
    'month': '%02d' % month,
TypeError: %d format: a number is required, not NoneType
```

**Comment by ludovicchabant** [comment]
Ah yeah, dammit. I'm still getting to know `setuptools` and I broke something with a recent change. It should now be fixed with a2d99ddff57060d8ffe59cad6dfa6a165fa41ab1.

The other bug you're getting should have been fixed with 99e2b9a41d567a4e16e861bbc7aa126a2d21950c, which should have been included if you installed from HEAD, so I'm not sure about this... maybe some more things to learn about `pip`...
