### ISSUE TITLE
can i use the markup of asciidoctor in piecrust

### ISSUE THREAD

**Issue by zaxebo1** [ludovicchabant/PieCrust2#20]
Asciidoctor( http://www.asciidoctor.org) is implemented in ruby language. I like its markup very much and conversant with it since long. 
Piecrust is in python,

**can i use Piecrust such that I do not need to use markdown , but rather may i use asciidoctor's asciidoc markup?** 
Please add this feature as plugin, if possible

**Comment by ludovicchabant** [comment]
Yes you can :) You'd have to write a [plugin](http://bolt80.com/piecrust/en/latest/code/) for that which defines a new "asciidoc" formatter (PieCrust comes by default with 2 formatters: markdown and textile) that would be available to you. The documentation for writing plugins is not the most exhaustive right now but feel free to ask if you're stuck.

However, I would recommend using the [Python version](http://asciidoc.org/) if possible, because running an external process (Ruby in this case) for every page would make the bake very slow unless your project is fairly small.

**Comment by zaxebo1** [comment]
Thanks. 
What i like about piecrust is that it can run dynamically as cms, and also as static site generator both. Kudos for bringing such a wonderful software.  :+1:

**Comment by ludovicchabant** [comment]
Thanks :)
