### ISSUE TITLE
Having problems with update piecrust 1.x to 2.x

### ISSUE THREAD

**Issue by magarciaguerra** [ludovicchabant/PieCrust2#21]
Hi, Ludovic!!

This is not an issue, actually it's my fault. I don't know what I have to do. Please, excuse me for my low coding skill :( 

May be, I'm asking a silly thing but I've tried almost everything I thought Anyway, sorry again...

I've downloaded last version of Python. I've installed Piecrust2 with Pip.

My PieCrust2 folder is this:

![issue001](https://cloud.githubusercontent.com/assets/4279626/8908440/6f8fde26-347c-11e5-8a3c-4d9a0083c126.gif)

And config.yml is like that:

![issue002](https://cloud.githubusercontent.com/assets/4279626/8908476/938b3de8-347c-11e5-89f4-1902da2291ec.gif)

So, let's bake site:

![issue003](https://cloud.githubusercontent.com/assets/4279626/8908484/a18da408-347c-11e5-8a9a-3f970485f9c3.gif)

And this is what I have: 
- Problems with routes
- Date problems and it affect to:
- Tag pages aren't baked
- Index pages aren't baked
- Archive page isn't baked
- Feed page isn't baked

![issue004](https://cloud.githubusercontent.com/assets/4279626/8908618/68281c6a-347d-11e5-8cf5-6023f3622fd5.gif)

Some code that I have:

![issue005](https://cloud.githubusercontent.com/assets/4279626/8908534/eb077d2a-347c-11e5-85be-ddc35397585e.gif)

![issue006](https://cloud.githubusercontent.com/assets/4279626/8908539/eede1e36-347c-11e5-9494-ad7ce1ae3b97.gif)

![issue007](https://cloud.githubusercontent.com/assets/4279626/8908542/f0fc1a92-347c-11e5-8b02-3ae072e636cd.gif)

![issue008](https://cloud.githubusercontent.com/assets/4279626/8908544/f2c99746-347c-11e5-8d76-eecf093d13ba.gif)

**Comment by ludovicchabant** [comment]
Hi! No need to apologize for being a beginner, we all start somewhere :)

How did you upgrade your website? Did you do it by hand, or did you use the `chef import` command? (if the latter, then there are bugs to fix!)

From what I can see, some of the problems are:

* Your blog posts are set to use a "shallow" organization, but from your error messages it looks like you have them organized in a "flat" organization? (i.e. all in the same `posts` folder) That's most probably the main problem, causing the route errors.
* The `baker/skip_patterns` has been renamed to `baker/ignore`.
* A bunch of your asset files have been left in the root folder, so they won't be copied to the output folder when you bake. You should probably move everything except `config.yml` to the `assets` folder... although you can probably get rid of `index.php`, along with the `baker/skip_patterns` config setting, since it looks like you're not really using it (it's probably a remnant of a very old version of PieCrust 1).

More information [here](http://bolt80.com/piecrust/en/latest/docs/importing/piecrust1/)

**Comment by magarciaguerra** [comment]
Hello, yes, I read  all the info and I import the old piecrust site. I get:

![issue109](https://cloud.githubusercontent.com/assets/4279626/8920075/566dd332-34c5-11e5-8489-aef2b7f7c764.gif)

It seems to be ok but folder is empty.

I tried again when I'm in this new folder calling bake import and, yes, I get an ok message but...It's very strage surf this new folder...

![issue110](https://cloud.githubusercontent.com/assets/4279626/8920124/cad43284-34c5-11e5-9ae8-463e6b46b204.gif)

Oh, yes, I have all posts (around 700) in same folder called posts

I don't know what I have to do. I'm completely lost :-(
Help, please :)

**Comment by ludovicchabant** [comment]
Ok so first I think maybe the `chef import` documentation is not totally clear... it looks like you're running `chef import piecrust1` from your _old_ website, and passing it the folder of your _new_ website... you should be doing the opposite, otherwise that's called "exporting", not "importing" :)  So you should be in the directory of the _new_ website (an empty website, with just a `config.yml` in it), calling `chef import piecrust1 /path/to/old/website`.

You can alternatively get in the _old_ website and run `chef import piecrust1 --upgrade`, and this will upgrade it "in place". **warning**: make sure you have a backup of your website before running this because it will move/rename/edit your files! 

I'll patch the `import piecrust1` command to give out more error messages if it figures you're running it from the wrong place...

**Comment by magarciaguerra** [comment]
It doesn't work.
I've imported the site to a new folder with config.yml and it only creates assets and _cache

![issue211](https://cloud.githubusercontent.com/assets/4279626/8925805/2b620cd0-350b-11e5-9370-f7d591225f45.gif)

**Comment by ludovicchabant** [comment]
Mmh there's probably a bug in the import code then. However it's working fine on simple test websites... could you send me a .zip file of your website so I can test with it? (assuming there's nothing private in there, but since it's published on the web I would assume not :) )

**Comment by magarciaguerra** [comment]
Ok, no problem :)
Thank you!!

I will send it you in a few minutes :)

**Comment by ludovicchabant** [comment]
Ok we resolved this via email, and the importer bug has been fixed.
