### ISSUE TITLE
Site/Root variable including tilde results in URI error upon baking

### ISSUE THREAD

**Issue by process91** [ludovicchabant/PieCrust2#24]
PieCrust is by far my favorite static site generator, and I love that it's been rewritten in Python. I noticed, however, in this version it seems like the "--portable" option which created relative links for everything is no longer available. I'm using PieCrust for a website which includes a tilde, typical of username based directories, and unfortunately it doesn't want to bake it that way.

For instance, with site.root defined as /~test/, it returns:

Errors found in ../../.virtualenvs/piecrust/lib/python3.4/site-packages/piecrust/resources/theme/pages/_index.html:
  URI '/%7Etest/' is not a full URI.

My workaround has been to assign the site root a unique string of characters, then run a recursive sed command to replace it with what it should be, but obviously I'd prefer to have this "baked in", so to speak.

**Comment by ludovicchabant** [comment]
Thanks! And yes, actually, when I moved to multi-core baking, I realized the old method for baking "portable" website wouldn't work so I "temporarily" dropped the feature... only to forget about it :(

So right now you're setting the `site.root` to something like `~johndoe`?

**Comment by process91** [comment]
Correct

Michael Boratko

**Comment by ludovicchabant** [comment]
Ok so now I remember why I dropped the `--portable` option: it forces PieCrust to disable caching because the same piece of content (say, a blog post) appearing in different places (say, main page + blog post + a few tag listings) potentially needs to be rendering as many times (because the links need to be rendered with different relative paths). This totally kills performance, and has limited use since there are many tools (Python itself being one) that can run a small webserver for previewing something.

As for PieCrust failing to bake when `site/root` has a tilde character in it (or any other non-ASCII character), that was definitely a bug. It should be fixed with 55ad794314d42fe701f0a5b350543d324070870c, but I haven't pushed a new version on PyPi yet because I'm not totally convinced yet that this fix hasn't introduced some subtle bug somewhere...

Thanks for reporting this!
