### ISSUE TITLE
site.root contains "/" even when set to ""

### ISSUE THREAD

**Issue by HendrikF** [ludovicchabant/PieCrust2#43]
PieCrust2 should accept the root being an empty string.

**Comment by HendrikF** [comment]
The same applies to `pcurl()` - It should not append a slash, when site.root is empty.

**Comment by ludovicchabant** [comment]
I'm not sure how an empty `site.root` would work? The expected behaviour is that if you're on any page (like, say, `pages/blah/foo.html`), a link with an `href` of `{{site.root}}` would take you back to the root. If that's an empty string, it would not do anything and you would be left on that `foo.html` page. I can't think of any good reason to have an empty site root but I'm probably missing some use case here?

**Comment by HendrikF** [comment]
Hmm, I am not sure, why I needed this. It was related to #44.
An empty site.root could indicate the use of relative urls.
