### ISSUE TITLE
Prebuild assets

### ISSUE THREAD

**Issue by TamiasSibiricus** [ludovicchabant/PieCrust2#48]
When i run `chef bake` assets run processor after pages and posts compilation process. Seems like normal workflow.
But it is not useful for amp static pages where custom css should included inline into page.  I think currently it is not problem for me cause i can include ready css file directly into template(i think). But i have some toughts to implement styles preprocessors like less or sass and styles. Postprocessing assets seems make it impossible directly with PieCrust2 config.
So question is: Is PieCrust2 have any possibility to run assests compilation before pages and posts processing?

Thanks for great and fast builder. :)

**Comment by ludovicchabant** [comment]
Hi! Sorry I let the support slide these past few months.

Technically there's nothing that prevents running asset processing before rather than after... but now with the 3.0 refactors it's actually running at the same time as the rest (it's being scheduled across your CPU cores in the same way), so it's a little tricky. It would either have to know about the dependency to schedule things correctly, or it would have to be done in 2 passes.

I guess at this point it would be easier to just run `chef` twice. I think you can run it once with only the assets (`chef bake -p asset`) and then run it with everything except the assets (`chef bake -p "-asset"`).
